// vocab.js
// IMPORTANT: it must assign into window.vocab
window.vocab = [
  // Verbs
  { "emoji": "🏃", "word": "correr", "type": "verb", "en": "to run", "jp": "走る" },
  { "emoji": "🍽️", "word": "comer", "type": "verb", "en": "to eat", "jp": "食べる" },
  { "emoji": "🎤", "word": "cantar", "type": "verb", "en": "to sing", "jp": "歌う" },
  { "emoji": "😴", "word": "dormir", "type": "verb", "en": "to sleep", "jp": "眠る" },
  { "emoji": "🎨", "word": "pintar", "type": "verb", "en": "to paint", "jp": "描く" },
  { "emoji": "📖", "word": "leer", "type": "verb", "en": "to read", "jp": "読む" },
  { "emoji": "🏊", "word": "nadar", "type": "verb", "en": "to swim", "jp": "泳ぐ" },
  { "emoji": "✍️", "word": "escribir", "type": "verb", "en": "to write", "jp": "書く" },
  { "emoji": "🚶", "word": "andar", "type": "verb", "en": "to walk", "jp": "歩く" },
  { "emoji": "😆", "word": "reír", "type": "verb", "en": "to laugh", "jp": "笑う" },
  { "emoji": "💃", "word": "bailar", "type": "verb", "en": "to dance", "jp": "踊る" },
  { "emoji": "📸", "word": "hacer fotos", "type": "verb", "en": "to take photos", "jp": "写真を撮る" },
  { "emoji": "🧹", "word": "limpiar", "type": "verb", "en": "to clean", "jp": "掃除する" },
  { "emoji": "🎲", "word": "jugar", "type": "verb", "en": "to play", "jp": "遊ぶ" },
  { "emoji": "🤗", "word": "abrazar", "type": "verb", "en": "to hug", "jp": "抱きしめる" },
  { "emoji": "🧩", "word": "montar", "type": "verb", "en": "to assemble", "jp": "組み立てる" },
  { "emoji": "🗣️", "word": "hablar", "type": "verb", "en": "to speak", "jp": "話す" },
  { "emoji": "👂", "word": "escuchar", "type": "verb", "en": "to listen", "jp": "聞く" },
  { "emoji": "👀", "word": "mirar", "type": "verb", "en": "to look", "jp": "見る" },
  { "emoji": "💭", "word": "pensar", "type": "verb", "en": "to think", "jp": "考える" },
  { "emoji": "🙋", "word": "saludar", "type": "verb", "en": "to greet", "jp": "挨拶する" },
  { "emoji": "🚴", "word": "pedalear", "type": "verb", "en": "to pedal", "jp": "ペダルを踏む" },
  { "emoji": "🎸", "word": "tocar", "type": "verb", "en": "to play (instrument)", "jp": "演奏する" },
  { "emoji": "🍳", "word": "cocinar", "type": "verb", "en": "to cook", "jp": "料理する" },
  { "emoji": "🛒", "word": "comprar", "type": "verb", "en": "to buy", "jp": "買う" },
  { "emoji": "🔍", "word": "buscar", "type": "verb", "en": "to search", "jp": "探す" },
  { "emoji": "🙏", "word": "rezar", "type": "verb", "en": "to pray", "jp": "祈る" },
  { "emoji": "🛌", "word": "descansar", "type": "verb", "en": "to rest", "jp": "休む" },
  { "emoji": "🎁", "word": "regalar", "type": "verb", "en": "to give", "jp": "贈る" },
  { "emoji": "🚀", "word": "volar", "type": "verb", "en": "to fly", "jp": "飛ぶ" },
  { "emoji": "🧘", "word": "meditar", "type": "verb", "en": "to meditate", "jp": "瞑想する" },
  { "emoji": "🏋️", "word": "levantar", "type": "verb", "en": "to lift", "jp": "持ち上げる" },
  { "emoji": "🤸", "word": "saltar", "type": "verb", "en": "to jump", "jp": "跳ぶ" },
  { "emoji": "🪓", "word": "cortar", "type": "verb", "en": "to cut", "jp": "切る" },
  { "emoji": "🎣", "word": "pescar", "type": "verb", "en": "to fish", "jp": "釣る" },
  { "emoji": "🧵", "word": "coser", "type": "verb", "en": "to sew", "jp": "縫う" },
  { "emoji": "🚪", "word": "abrir", "type": "verb", "en": "to open", "jp": "開ける" },
  { "emoji": "🔒", "word": "cerrar", "type": "verb", "en": "to close", "jp": "閉める" },
  { "emoji": "🖱️", "word": "clicar", "type": "verb", "en": "to click", "jp": "クリックする" },
  { "emoji": "⌨️", "word": "teclear", "type": "verb", "en": "to type", "jp": "タイプする" },
  { "emoji": "📞", "word": "llamar", "type": "verb", "en": "to call", "jp": "電話する" },
  { "emoji": "📧", "word": "enviar", "type": "verb", "en": "to send", "jp": "送る" },
  { "emoji": "💡", "word": "encender", "type": "verb", "en": "to turn on", "jp": "点ける" },
  { "emoji": "🛑", "word": "parar", "type": "verb", "en": "to stop", "jp": "止める" },
  { "emoji": "▶️", "word": "empezar", "type": "verb", "en": "to start", "jp": "始める" },
  { "emoji": "⏹️", "word": "terminar", "type": "verb", "en": "to finish", "jp": "終える" },
  { "emoji": "🎬", "word": "grabar", "type": "verb", "en": "to film", "jp": "撮影する" },
  { "emoji": "📢", "word": "anunciar", "type": "verb", "en": "to announce", "jp": "発表する" },
  { "emoji": "👊", "word": "golpear", "type": "verb", "en": "to hit", "jp": "打つ" },
  { "emoji": "🤝", "word": "apretar", "type": "verb", "en": "to squeeze", "jp": "握る" },
  { "emoji": "🛠️", "word": "arreglar", "type": "verb", "en": "to fix", "jp": "修理する" },
  { "emoji": "🎯", "word": "apuntar", "type": "verb", "en": "to aim", "jp": "狙う" },
  { "emoji": "🪂", "word": "lanzar", "type": "verb", "en": "to throw", "jp": "投げる" },
  { "emoji": "🧳", "word": "viajar", "type": "verb", "en": "to travel", "jp": "旅行する" },
  { "emoji": "🪴", "word": "plantar", "type": "verb", "en": "to plant", "jp": "植える" },
  { "emoji": "💦", "word": "regar", "type": "verb", "en": "to water", "jp": "水をやる" },
  { "emoji": "🧺", "word": "lavar", "type": "verb", "en": "to wash", "jp": "洗う" },
  { "emoji": "🧼", "word": "enjabonar", "type": "verb", "en": "to soap", "jp": "石鹸をつける" },
  { "emoji": "🪡", "word": "bordar", "type": "verb", "en": "to embroider", "jp": "刺繍する" },
  { "emoji": "🧬", "word": "investigar", "type": "verb", "en": "to research", "jp": "研究する" },
  { "emoji": "📝", "word": "apuntar", "type": "verb", "en": "to note", "jp": "メモする" },
  { "emoji": "🪜", "word": "subir", "type": "verb", "en": "to go up", "jp": "上がる" },
  { "emoji": "🪜", "word": "bajar", "type": "verb", "en": "to go down", "jp": "下がる" },
  { "emoji": "🏄", "word": "hacer surf", "type": "verb", "en": "to surf", "jp": "サーフィンする" },
  { "emoji": "⛷️", "word": "esquiar", "type": "verb", "en": "to ski", "jp": "スキーする" },
  { "emoji": "🚣", "word": "remar", "type": "verb", "en": "to row", "jp": "漕ぐ" },
  { "emoji": "🥁", "word": "tocar el tambor", "type": "verb", "en": "to drum", "jp": "ドラムを叩く" },
  { "emoji": "🪗", "word": "tocar el acordeón", "type": "verb", "en": "to play accordion", "jp": "アコーディオンを弾く" },
  { "emoji": "🎳", "word": "jugar a los bolos", "type": "verb", "en": "to bowl", "jp": "ボウリングをする" },

  // Nouns (Animals)
  { "emoji": "🐶", "word": "perro", "type": "noun", "en": "dog", "jp": "犬" },
  { "emoji": "🐱", "word": "gato", "type": "noun", "en": "cat", "jp": "猫" },
  { "emoji": "🦒", "word": "jirafa", "type": "noun", "en": "giraffe", "jp": "キリン" },
  { "emoji": "🦁", "word": "león", "type": "noun", "en": "lion", "jp": "ライオン" },
  { "emoji": "🐠", "word": "pez", "type": "noun", "en": "fish", "jp": "魚" },
  { "emoji": "🐦", "word": "pájaro", "type": "noun", "en": "bird", "jp": "鳥" },
  { "emoji": "🐮", "word": "vaca", "type": "noun", "en": "cow", "jp": "牛" },
  { "emoji": "🐷", "word": "cerdo", "type": "noun", "en": "pig", "jp": "豚" },
  { "emoji": "🐘", "word": "elefante", "type": "noun", "en": "elephant", "jp": "象" },
  { "emoji": "🐰", "word": "conejo", "type": "noun", "en": "rabbit", "jp": "ウサギ" },
  { "emoji": "🦓", "word": "cebra", "type": "noun", "en": "zebra", "jp": "シマウマ" },
  { "emoji": "🐢", "word": "tortuga", "type": "noun", "en": "turtle", "jp": "カメ" },
  { "emoji": "🐙", "word": "pulpo", "type": "noun", "en": "octopus", "jp": "タコ" },
  { "emoji": "🦚", "word": "pavo real", "type": "noun", "en": "peacock", "jp": "クジャク" },
  { "emoji": "🐬", "word": "delfín", "type": "noun", "en": "dolphin", "jp": "イルカ" },
  { "emoji": "🦘", "word": "canguro", "type": "noun", "en": "kangaroo", "jp": "カンガルー" },
  { "emoji": "🦔", "word": "erizo", "type": "noun", "en": "hedgehog", "jp": "ハリネズミ" },
  { "emoji": "🐴", "word": "caballo", "type": "noun", "en": "horse", "jp": "馬" },
  { "emoji": "🐍", "word": "serpiente", "type": "noun", "en": "snake", "jp": "蛇" },
  { "emoji": "🦊", "word": "zorro", "type": "noun", "en": "fox", "jp": "キツネ" },
  { "emoji": "🐻", "word": "oso", "type": "noun", "en": "bear", "jp": "クマ" },
  { "emoji": "🐺", "word": "lobo", "type": "noun", "en": "wolf", "jp": "オオカミ" },
  { "emoji": "🦌", "word": "ciervo", "type": "noun", "en": "deer", "jp": "鹿" },
  { "emoji": "🐐", "word": "cabra", "type": "noun", "en": "goat", "jp": "ヤギ" },
  { "emoji": "🐑", "word": "oveja", "type": "noun", "en": "sheep", "jp": "羊" },
  { "emoji": "🦜", "word": "loro", "type": "noun", "en": "parrot", "jp": "オウム" },
  { "emoji": "🦢", "word": "cisne", "type": "noun", "en": "swan", "jp": "白鳥" },
  { "emoji": "🦝", "word": "mapache", "type": "noun", "en": "raccoon", "jp": "アライグマ" },
  { "emoji": "🐟", "word": "pescado", "type": "noun", "en": "fish (food)", "jp": "魚（食材）" },
  { "emoji": "🦈", "word": "tiburón", "type": "noun", "en": "shark", "jp": "サメ" },
  { "emoji": "🐳", "word": "ballena", "type": "noun", "en": "whale", "jp": "クジラ" },
  { "emoji": "🦋", "word": "mariposa", "type": "noun", "en": "butterfly", "jp": "蝶" },
  { "emoji": "🐝", "word": "abeja", "type": "noun", "en": "bee", "jp": "蜂" },
  { "emoji": "🐞", "word": "mariquita", "type": "noun", "en": "ladybug", "jp": "てんとう虫" },
  { "emoji": "🦂", "word": "escorpión", "type": "noun", "en": "scorpion", "jp": "サソリ" },
  { "emoji": "🕷️", "word": "araña", "type": "noun", "en": "spider", "jp": "蜘蛛" },
  { "emoji": "🦗", "word": "grillo", "type": "noun", "en": "cricket", "jp": "コオロギ" },
  { "emoji": "🐜", "word": "hormiga", "type": "noun", "en": "ant", "jp": "アリ" },
  { "emoji": "🦟", "word": "mosquito", "type": "noun", "en": "mosquito", "jp": "蚊" },
  { "emoji": "🦎", "word": "lagarto", "type": "noun", "en": "lizard", "jp": "トカゲ" },
  { "emoji": "🐊", "word": "cocodrilo", "type": "noun", "en": "crocodile", "jp": "ワニ" },
  { "emoji": "🦖", "word": "dinosaurio", "type": "noun", "en": "dinosaur", "jp": "恐竜" },
  { "emoji": "🦍", "word": "gorila", "type": "noun", "en": "gorilla", "jp": "ゴリラ" },
  { "emoji": "🦛", "word": "hipopótamo", "type": "noun", "en": "hippopotamus", "jp": "カバ" },
  { "emoji": "🐅", "word": "tigre", "type": "noun", "en": "tiger", "jp": "虎" },
  { "emoji": "🐆", "word": "leopardo", "type": "noun", "en": "leopard", "jp": "ヒョウ" },
  { "emoji": "🦬", "word": "búfalo", "type": "noun", "en": "buffalo", "jp": "バッファロー" },
  { "emoji": "🐪", "word": "camello", "type": "noun", "en": "camel", "jp": "ラクダ" },
  { "emoji": "🦙", "word": "llama", "type": "noun", "en": "llama", "jp": "ラマ" },
  { "emoji": "🦦", "word": "nutria", "type": "noun", "en": "otter", "jp": "カワウソ" },
  { "emoji": "🦡", "word": "tejón", "type": "noun", "en": "badger", "jp": "アナグマ" },
  { "emoji": "🦥", "word": "perezoso", "type": "noun", "en": "sloth", "jp": "ナマケモノ" },
  { "emoji": "🦣", "word": "mamut", "type": "noun", "en": "mammoth", "jp": "マンモス" },
  { "emoji": "🦅", "word": "águila", "type": "noun", "en": "eagle", "jp": "鷲" },
  { "emoji": "🦉", "word": "búho", "type": "noun", "en": "owl", "jp": "フクロウ" },
  { "emoji": "🦇", "word": "murciélago", "type": "noun", "en": "bat", "jp": "コウモリ" },
  { "emoji": "🐿️", "word": "ardilla", "type": "noun", "en": "squirrel", "jp": "リス" },
  { "emoji": "🦨", "word": "mofeta", "type": "noun", "en": "skunk", "jp": "スカンク" },
  { "emoji": "🐀", "word": "rata", "type": "noun", "en": "rat", "jp": "ネズミ" },
  { "emoji": "🐁", "word": "ratón", "type": "noun", "en": "mouse", "jp": "ハツカネズミ" },
  { "emoji": "🦫", "word": "castor", "type": "noun", "en": "beaver", "jp": "ビーバー" },
  { "emoji": "🐧", "word": "pingüino", "type": "noun", "en": "penguin", "jp": "ペンギン" },
  { "emoji": "🐣", "word": "pollito", "type": "noun", "en": "chick", "jp": "ひよこ" },
  { "emoji": "🐔", "word": "gallina", "type": "noun", "en": "hen", "jp": "めんどり" },
  { "emoji": "🦃", "word": "pavo", "type": "noun", "en": "turkey", "jp": "七面鳥" },
  { "emoji": "🦆", "word": "pato", "type": "noun", "en": "duck", "jp": "アヒル" },
  { "emoji": "🦩", "word": "flamenco", "type": "noun", "en": "flamingo", "jp": "フラミンゴ" },
  { "emoji": "🐓", "word": "gallo", "type": "noun", "en": "rooster", "jp": "おんどり" },
  { "emoji": "🐕", "word": "perrito", "type": "noun", "en": "puppy", "jp": "子犬" },
  { "emoji": "🐈", "word": "gatito", "type": "noun", "en": "kitten", "jp": "子猫" },
  { "emoji": "🦤", "word": "dodo", "type": "noun", "en": "dodo", "jp": "ドードー" },
  { "emoji": "🦪", "word": "ostra", "type": "noun", "en": "oyster", "jp": "カキ" },

  // Nouns (Body Parts)
  { "emoji": "✋", "word": "mano", "type": "noun", "en": "hand", "jp": "手" },
  { "emoji": "👁️", "word": "ojo", "type": "noun", "en": "eye", "jp": "目" },
  { "emoji": "👂", "word": "oreja", "type": "noun", "en": "ear", "jp": "耳" },
  { "emoji": "👃", "word": "nariz", "type": "noun", "en": "nose", "jp": "鼻" },
  { "emoji": "👄", "word": "boca", "type": "noun", "en": "mouth", "jp": "口" },
  { "emoji": "🦶", "word": "pie", "type": "noun", "en": "foot", "jp": "足" },
  { "emoji": "🦵", "word": "pierna", "type": "noun", "en": "leg", "jp": "脚" },
  { "emoji": "💪", "word": "brazo", "type": "noun", "en": "arm", "jp": "腕" },
  { "emoji": "🧠", "word": "cerebro", "type": "noun", "en": "brain", "jp": "脳" },
  { "emoji": "❤️", "word": "corazón", "type": "noun", "en": "heart", "jp": "心臓" },
  { "emoji": "🦷", "word": "diente", "type": "noun", "en": "tooth", "jp": "歯" },
  { "emoji": "🦴", "word": "hueso", "type": "noun", "en": "bone", "jp": "骨" },
  { "emoji": "👅", "word": "lengua", "type": "noun", "en": "tongue", "jp": "舌" },
  { "emoji": "🫁", "word": "pulmón", "type": "noun", "en": "lung", "jp": "肺" },
  { "emoji": "🫀", "word": "estómago", "type": "noun", "en": "stomach", "jp": "胃" },
  { "emoji": "🦾", "word": "antebrazo", "type": "noun", "en": "forearm", "jp": "前腕" },
  { "emoji": "🦿", "word": "rodilla", "type": "noun", "en": "knee", "jp": "膝" },
  { "emoji": "🦻", "word": "oído", "type": "noun", "en": "inner ear", "jp": "内耳" },
  { "emoji": "👤", "word": "cabeza", "type": "noun", "en": "head", "jp": "頭" },
  { "emoji": "💇", "word": "pelo", "type": "noun", "en": "hair", "jp": "髪" },
  { "emoji": "🧔", "word": "barba", "type": "noun", "en": "beard", "jp": "ひげ" },
  { "emoji": "👩‍🦰", "word": "melena", "type": "noun", "en": "mane", "jp": "たてがみ" },
  { "emoji": "👶", "word": "bebé", "type": "noun", "en": "baby", "jp": "赤ちゃん" },
  { "emoji": "🧑", "word": "persona", "type": "noun", "en": "person", "jp": "人" },
  { "emoji": "👈", "word": "dedo", "type": "noun", "en": "finger", "jp": "指" },
  { "emoji": "👍", "word": "pulgar", "type": "noun", "en": "thumb", "jp": "親指" },
  { "emoji": "👌", "word": "índice", "type": "noun", "en": "index finger", "jp": "人差し指" },
  { "emoji": "🖖", "word": "palma", "type": "noun", "en": "palm", "jp": "手のひら" },
  { "emoji": "🤚", "word": "muñeca", "type": "noun", "en": "wrist", "jp": "手首" },
  { "emoji": "🦶", "word": "talón", "type": "noun", "en": "heel", "jp": "かかと" },
  { "emoji": "👣", "word": "huella", "type": "noun", "en": "footprint", "jp": "足跡" },
  { "emoji": "🦵", "word": "muslo", "type": "noun", "en": "thigh", "jp": "太もも" },
  { "emoji": "🦿", "word": "tobillo", "type": "noun", "en": "ankle", "jp": "足首" },
  { "emoji": "💪", "word": "músculo", "type": "noun", "en": "muscle", "jp": "筋肉" },
  { "emoji": "🦴", "word": "cráneo", "type": "noun", "en": "skull", "jp": "頭蓋骨" },
  { "emoji": "🦷", "word": "muela", "type": "noun", "en": "molar", "jp": "臼歯" },
  { "emoji": "👁️‍🗨️", "word": "pupila", "type": "noun", "en": "pupil", "jp": "瞳孔" },
  { "emoji": "🧔‍♀️", "word": "bigote", "type": "noun", "en": "mustache", "jp": "口ひげ" },
  { "emoji": "👩‍🦲", "word": "cuero cabelludo", "type": "noun", "en": "scalp", "jp": "頭皮" },
  { "emoji": "🫂", "word": "espalda", "type": "noun", "en": "back", "jp": "背中" },
  { "emoji": "🦶", "word": "dedos del pie", "type": "noun", "en": "toes", "jp": "足の指" },
  { "emoji": "🦵", "word": "cadera", "type": "noun", "en": "hip", "jp": "腰" },
  { "emoji": "🦿", "word": "pantorrilla", "type": "noun", "en": "calf", "jp": "ふくらはぎ" },
  { "emoji": "🦴", "word": "costilla", "type": "noun", "en": "rib", "jp": "肋骨" },
  { "emoji": "🫁", "word": "hígado", "type": "noun", "en": "liver", "jp": "肝臓" },
  { "emoji": "🫀", "word": "riñón", "type": "noun", "en": "kidney", "jp": "腎臓" },
  { "emoji": "🦷", "word": "encía", "type": "noun", "en": "gum", "jp": "歯茎" },
  { "emoji": "👄", "word": "labio", "type": "noun", "en": "lip", "jp": "唇" },
  { "emoji": "👁️", "word": "párpado", "type": "noun", "en": "eyelid", "jp": "まぶた" },
  { "emoji": "👩‍🦰", "word": "ceja", "type": "noun", "en": "eyebrow", "jp": "眉毛" },

  // Nouns (Clothing)
  { "emoji": "👕", "word": "camiseta", "type": "noun", "en": "t-shirt", "jp": "Tシャツ" },
  { "emoji": "👖", "word": "pantalones", "type": "noun", "en": "pants", "jp": "ズボン" },
  { "emoji": "👔", "word": "corbata", "type": "noun", "en": "tie", "jp": "ネクタイ" },
  { "emoji": "👞", "word": "zapatos", "type": "noun", "en": "shoes", "jp": "靴" },
  { "emoji": "👗", "word": "vestido", "type": "noun", "en": "dress", "jp": "ドレス" },
  { "emoji": "🧥", "word": "abrigo", "type": "noun", "en": "coat", "jp": "コート" },
  { "emoji": "🧢", "word": "gorra", "type": "noun", "en": "cap", "jp": "キャップ" },
  { "emoji": "🧣", "word": "bufanda", "type": "noun", "en": "scarf", "jp": "スカーフ" },
  { "emoji": "🧤", "word": "guantes", "type": "noun", "en": "gloves", "jp": "手袋" },
  { "emoji": "🧦", "word": "calcetines", "type": "noun", "en": "socks", "jp": "靴下" },
  { "emoji": "👟", "word": "zapatillas", "type": "noun", "en": "sneakers", "jp": "スニーカー" },
  { "emoji": "👢", "word": "botas", "type": "noun", "en": "boots", "jp": "ブーツ" },
  { "emoji": "👡", "word": "sandalias", "type": "noun", "en": "sandals", "jp": "サンダル" },
  { "emoji": "👠", "word": "tacones", "type": "noun", "en": "heels", "jp": "ヒール" },
  { "emoji": "🥾", "word": "botas de montaña", "type": "noun", "en": "hiking boots", "jp": "登山靴" },
  { "emoji": "👘", "word": "kimono", "type": "noun", "en": "kimono", "jp": "着物" },
  { "emoji": "🩱", "word": "bañador", "type": "noun", "en": "swimsuit", "jp": "水着" },
  { "emoji": "🩳", "word": "pantalones cortos", "type": "noun", "en": "shorts", "jp": "ショーツ" },
  { "emoji": "👙", "word": "bikini", "type": "noun", "en": "bikini", "jp": "ビキニ" },
  { "emoji": "🧺", "word": "cesto de la ropa", "type": "noun", "en": "laundry basket", "jp": "洗濯かご" },
  { "emoji": "👚", "word": "blusa", "type": "noun", "en": "blouse", "jp": "ブラウス" },
  { "emoji": "🥼", "word": "bata", "type": "noun", "en": "robe", "jp": "ガウン" },
  { "emoji": "🧳", "word": "maleta", "type": "noun", "en": "suitcase", "jp": "スーツケース" },
  { "emoji": "🎩", "word": "sombrero", "type": "noun", "en": "hat", "jp": "帽子" },
  { "emoji": "👒", "word": "sombrerito", "type": "noun", "en": "bonnet", "jp": "ボンネット" },
  { "emoji": "🪖", "word": "casco", "type": "noun", "en": "helmet", "jp": "ヘルメット" },
  { "emoji": "👓", "word": "gafas", "type": "noun", "en": "glasses", "jp": "眼鏡" },
  { "emoji": "🕶️", "word": "gafas de sol", "type": "noun", "en": "sunglasses", "jp": "サングラス" },
  { "emoji": "⌚", "word": "reloj", "type": "noun", "en": "watch", "jp": "時計" },
  { "emoji": "💍", "word": "anillo", "type": "noun", "en": "ring", "jp": "指輪" },
  { "emoji": "📿", "word": "collar", "type": "noun", "en": "necklace", "jp": "ネックレス" },
  { "emoji": "💎", "word": "joya", "type": "noun", "en": "jewel", "jp": "宝石" },
  { "emoji": "👑", "word": "corona", "type": "noun", "en": "crown", "jp": "王冠" },
  { "emoji": "🧷", "word": "imperdible", "type": "noun", "en": "safety pin", "jp": "安全ピン" },
  { "emoji": "💼", "word": "maletín", "type": "noun", "en": "briefcase", "jp": "ブリーフケース" },
  { "emoji": "🎒", "word": "mochila", "type": "noun", "en": "backpack", "jp": "リュックサック" },
  { "emoji": "👜", "word": "bolso", "type": "noun", "en": "purse", "jp": "ハンドバッグ" },
  { "emoji": "👛", "word": "monedero", "type": "noun", "en": "wallet", "jp": "財布" },
  { "emoji": "🩴", "word": "chanclas", "type": "noun", "en": "flip-flops", "jp": "ビーチサンダル" },
  { "emoji": "🧵", "word": "hilo", "type": "noun", "en": "thread", "jp": "糸" },
  { "emoji": "🪡", "word": "aguja", "type": "noun", "en": "needle", "jp": "針" },
  { "emoji": "🧶", "word": "lana", "type": "noun", "en": "wool", "jp": "毛糸" },
  { "emoji": "👝", "word": "cartera", "type": "noun", "en": "clutch", "jp": "クラッチバッグ" },
  { "emoji": "🧴", "word": "perfume", "type": "noun", "en": "perfume", "jp": "香水" },
  { "emoji": "💄", "word": "pintalabios", "type": "noun", "en": "lipstick", "jp": "口紅" },
  { "emoji": "💅", "word": "esmalte", "type": "noun", "en": "nail polish", "jp": "ネイルポリッシュ" },
  { "emoji": "🪒", "word": "maquinilla", "type": "noun", "en": "razor", "jp": "かみそり" },
  { "emoji": "🪥", "word": "cepillo de dientes", "type": "noun", "en": "toothbrush", "jp": "歯ブラシ" },
  { "emoji": "🪞", "word": "espejo", "type": "noun", "en": "mirror", "jp": "鏡" },
  { "emoji": "🧼", "word": "jabón", "type": "noun", "en": "soap", "jp": "石鹸" },
  { "emoji": "🧴", "word": "champú", "type": "noun", "en": "shampoo", "jp": "シャンプー" },
  { "emoji": "🩲", "word": "calzoncillos", "type": "noun", "en": "underwear", "jp": "下着" },
  { "emoji": "🧑‍🚒", "word": "uniforme", "type": "noun", "en": "uniform", "jp": "制服" },
  { "emoji": "🧑‍🎓", "word": "toga", "type": "noun", "en": "gown", "jp": "ガウン" },
  { "emoji": "🧑‍⚕️", "word": "bata de médico", "type": "noun", "en": "doctor's coat", "jp": "医師の白衣" },
  { "emoji": "🧑‍🍳", "word": "delantal", "type": "noun", "en": "apron", "jp": "エプロン" },
  { "emoji": "🧑‍🎤", "word": "disfraz", "type": "noun", "en": "costume", "jp": "衣装" },
  { "emoji": "🧑‍🏭", "word": "mono", "type": "noun", "en": "overalls", "jp": "作業着" },
  { "emoji": "🧑‍✈️", "word": "uniforme de piloto", "type": "noun", "en": "pilot uniform", "jp": "パイロット制服" },
  { "emoji": "🧑‍🚀", "word": "traje espacial", "type": "noun", "en": "space suit", "jp": "宇宙服" },

  // Adjectives (Colors)
  { "emoji": "🔴", "word": "rojo", "type": "adjective", "en": "red", "jp": "赤" },
  { "emoji": "🟢", "word": "verde", "type": "adjective", "en": "green", "jp": "緑" },
  { "emoji": "🔵", "word": "azul", "type": "adjective", "en": "blue", "jp": "青" },
  { "emoji": "💛", "word": "amarillo", "type": "adjective", "en": "yellow", "jp": "黄色" },
  { "emoji": "🟣", "word": "morado", "type": "adjective", "en": "purple", "jp": "紫" },
  { "emoji": "🟤", "word": "marrón", "type": "adjective", "en": "brown", "jp": "茶色" },
  { "emoji": "⚪", "word": "blanco", "type": "adjective", "en": "white", "jp": "白" },
  { "emoji": "🖤", "word": "negro", "type": "adjective", "en": "black", "jp": "黒" },
  { "emoji": "🧡", "word": "naranja", "type": "adjective", "en": "orange", "jp": "オレンジ" },
  { "emoji": "🩷", "word": "rosa", "type": "adjective", "en": "pink", "jp": "ピンク" },
  { "emoji": "⚫", "word": "gris", "type": "adjective", "en": "gray", "jp": "灰色" },
  { "emoji": "🩶", "word": "plateado", "type": "adjective", "en": "silver", "jp": "銀色" },
  { "emoji": "🟡", "word": "dorado", "type": "adjective", "en": "gold", "jp": "金色" },
  { "emoji": "🩵", "word": "turquesa", "type": "adjective", "en": "turquoise", "jp": "ターコイズ" },
  { "emoji": "🟠", "word": "naranja", "type": "adjective", "en": "orange", "jp": "オレンジ" },
  { "emoji": "🟥", "word": "escarlata", "type": "adjective", "en": "scarlet", "jp": "スカーレット" },
  { "emoji": "🟩", "word": "esmeralda", "type": "adjective", "en": "emerald", "jp": "エメラルド" },
  { "emoji": "🟦", "word": "celeste", "type": "adjective", "en": "sky blue", "jp": "空色" },
  { "emoji": "🟨", "word": "ámbar", "type": "adjective", "en": "amber", "jp": "琥珀色" },
  { "emoji": "🟪", "word": "púrpura", "type": "adjective", "en": "purple", "jp": "紫" },
  { "emoji": "🟫", "word": "café", "type": "adjective", "en": "brown", "jp": "茶色" },
  { "emoji": "🟦", "word": "añil", "type": "adjective", "en": "indigo", "jp": "藍色" },

  // Adjectives (Emotions)
  { "emoji": "😄", "word": "feliz", "type": "adjective", "en": "happy", "jp": "幸せ" },
  { "emoji": "😊", "word": "contento", "type": "adjective", "en": "content", "jp": "満足" },
  { "emoji": "😢", "word": "triste", "type": "adjective", "en": "sad", "jp": "悲しい" },
  { "emoji": "😡", "word": "enfadado", "type": "adjective", "en": "angry", "jp": "怒っている" },
  { "emoji": "😎", "word": "guay", "type": "adjective", "en": "cool", "jp": "かっこいい" },
  { "emoji": "😇", "word": "amable", "type": "adjective", "en": "kind", "jp": "親切" },
  { "emoji": "😋", "word": "sabroso", "type": "adjective", "en": "tasty", "jp": "おいしい" },
  { "emoji": "😜", "word": "loco", "type": "adjective", "en": "crazy", "jp": "狂った" },
  { "emoji": "😱", "word": "asustado", "type": "adjective", "en": "scared", "jp": "怖がっている" },
  { "emoji": "🥰", "word": "enamorado", "type": "adjective", "en": "in love", "jp": "恋をしている" },
  { "emoji": "😴", "word": "cansado", "type": "adjective", "en": "tired", "jp": "疲れた" },
  { "emoji": "😣", "word": "frustrado", "type": "adjective", "en": "frustrated", "jp": "欲求不満" },
  { "emoji": "😞", "word": "deprimido", "type": "adjective", "en": "depressed", "jp": "落ち込んだ" },
  { "emoji": "😖", "word": "avergonzado", "type": "adjective", "en": "embarrassed", "jp": "恥ずかしい" },
  { "emoji": "😫", "word": "agotado", "type": "adjective", "en": "exhausted", "jp": "疲れ果てた" },
  { "emoji": "😤", "word": "furioso", "type": "adjective", "en": "furious", "jp": "激怒した" },
  { "emoji": "😳", "word": "sorprendido", "type": "adjective", "en": "surprised", "jp": "驚いた" },
  { "emoji": "😥", "word": "decepcionado", "type": "adjective", "en": "disappointed", "jp": "失望した" },
  { "emoji": "😍", "word": "encantado", "type": "adjective", "en": "delighted", "jp": "喜んで" },
  { "emoji": "😬", "word": "nervioso", "type": "adjective", "en": "nervous", "jp": "緊張した" },
  { "emoji": "😪", "word": "somnoliento", "type": "adjective", "en": "sleepy", "jp": "眠い" },
  { "emoji": "😟", "word": "preocupado", "type": "adjective", "en": "worried", "jp": "心配" },
  { "emoji": "😠", "word": "irritado", "type": "adjective", "en": "irritated", "jp": "イライラした" },
  { "emoji": "😘", "word": "cariñoso", "type": "adjective", "en": "affectionate", "jp": "愛情深い" },
  { "emoji": "😭", "word": "lloroso", "type": "adjective", "en": "tearful", "jp": "涙ぐんだ" },
  { "emoji": "🤗", "word": "afectuoso", "type": "adjective", "en": "loving", "jp": "愛情のある" },
  { "emoji": "😆", "word": "divertido", "type": "adjective", "en": "funny", "jp": "面白い" },
  { "emoji": "😓", "word": "sudoroso", "type": "adjective", "en": "sweaty", "jp": "汗だく" },
  { "emoji": "😵", "word": "mareado", "type": "adjective", "en": "dizzy", "jp": "めまいがする" },
  { "emoji": "😷", "word": "enfermo", "type": "adjective", "en": "sick", "jp": "病気" },
  { "emoji": "🤩", "word": "emocionado", "type": "adjective", "en": "excited", "jp": "興奮した" },
  { "emoji": "😰", "word": "ansioso", "type": "adjective", "en": "anxious", "jp": "不安な" },
  { "emoji": "😶", "word": "silencioso", "type": "adjective", "en": "silent", "jp": "静かな" },
  { "emoji": "😑", "word": "aburrido", "type": "adjective", "en": "bored", "jp": "退屈" },
  { "emoji": "😣", "word": "dolorido", "type": "adjective", "en": "sore", "jp": "痛い" },
  { "emoji": "😈", "word": "malvado", "type": "adjective", "en": "evil", "jp": "邪悪な" },
  { "emoji": "😌", "word": "relajado", "type": "adjective", "en": "relaxed", "jp": "リラックスした" },
  { "emoji": "😔", "word": "melancólico", "type": "adjective", "en": "melancholic", "jp": "憂鬱な" },
  { "emoji": "😚", "word": "tierno", "type": "adjective", "en": "tender", "jp": "優しい" },
  { "emoji": "😝", "word": "burlón", "type": "adjective", "en": "teasing", "jp": "からかう" },
  { "emoji": "😒", "word": "descontento", "type": "adjective", "en": "discontent", "jp": "不満" },
  { "emoji": "😕", "word": "confundido", "type": "adjective", "en": "confused", "jp": "混乱した" },
  { "emoji": "😮", "word": "asombrado", "type": "adjective", "en": "amazed", "jp": "驚いた" },
  { "emoji": "😧", "word": "angustiado", "type": "adjective", "en": "distressed", "jp": "苦悩した" },
  { "emoji": "😲", "word": "atónito", "type": "adjective", "en": "astonished", "jp": "驚愕した" },
  { "emoji": "😏", "word": "sarcástico", "type": "adjective", "en": "sarcastic", "jp": "皮肉な" },
  { "emoji": "😉", "word": "juguetón", "type": "adjective", "en": "playful", "jp": "遊び心のある" },
  { "emoji": "🥳", "word": "festivo", "type": "adjective", "en": "festive", "jp": "お祭り気分の" },

  // Nouns (Other)
  { "emoji": "❤️", "word": "amor", "type": "noun", "en": "love", "jp": "愛" },
  { "emoji": "💔", "word": "desamor", "type": "noun", "en": "heartbreak", "jp": "失恋" },
  { "emoji": "🍎", "word": "manzana", "type": "noun", "en": "apple", "jp": "りんご" },
  { "emoji": "🍕", "word": "pizza", "type": "noun", "en": "pizza", "jp": "ピザ" },
  { "emoji": "💧", "word": "agua", "type": "noun", "en": "water", "jp": "水" },
  { "emoji": "🍓", "word": "fresa", "type": "noun", "en": "strawberry", "jp": "いちご" },
  { "emoji": "🍋", "word": "limón", "type": "noun", "en": "lemon", "jp": "レモン" },
  { "emoji": "🍉", "word": "sandía", "type": "noun", "en": "watermelon", "jp": "スイカ" },
  { "emoji": "🍫", "word": "chocolate", "type": "noun", "en": "chocolate", "jp": "チョコレート" },
  { "emoji": "🍝", "word": "pasta", "type": "noun", "en": "pasta", "jp": "パスタ" },
  { "emoji": "🍟", "word": "patatas fritas", "type": "noun", "en": "french fries", "jp": "フライドポテト" },
  { "emoji": "🍦", "word": "helado", "type": "noun", "en": "ice cream", "jp": "アイスクリーム" },
  { "emoji": "🍬", "word": "caramelo", "type": "noun", "en": "candy", "jp": "キャンディ" },
  { "emoji": "🍇", "word": "uvas", "type": "noun", "en": "grapes", "jp": "ぶどう" },
  { "emoji": "🍰", "word": "tarta", "type": "noun", "en": "cake", "jp": "ケーキ" },
  { "emoji": "🥐", "word": "croissant", "type": "noun", "en": "croissant", "jp": "クロワッサン" },
  { "emoji": "🍂", "word": "hoja", "type": "noun", "en": "leaf", "jp": "葉" },
  { "emoji": "🥛", "word": "leche", "type": "noun", "en": "milk", "jp": "牛乳" },
  { "emoji": "🍊", "word": "naranja", "type": "noun", "en": "orange", "jp": "オレンジ" },
  { "emoji": "🍍", "word": "piña", "type": "noun", "en": "pineapple", "jp": "パイナップル" },
  { "emoji": "🍌", "word": "plátano", "type": "noun", "en": "banana", "jp": "バナナ" },
  { "emoji": "🍑", "word": "melocotón", "type": "noun", "en": "peach", "jp": "桃" },
  { "emoji": "🍈", "word": "melón", "type": "noun", "en": "melon", "jp": "メロン" },
  { "emoji": "🥭", "word": "mango", "type": "noun", "en": "mango", "jp": "マンゴー" },
  { "emoji": "🥝", "word": "kiwi", "type": "noun", "en": "kiwi", "jp": "キウイ" },
  { "emoji": "🍒", "word": "cereza", "type": "noun", "en": "cherry", "jp": "さくらんぼ" },
  { "emoji": "🥥", "word": "coco", "type": "noun", "en": "coconut", "jp": "ココナッツ" },
  { "emoji": "🍆", "word": "berenjena", "type": "noun", "en": "eggplant", "jp": "なす" },
  { "emoji": "🥕", "word": "zanahoria", "type": "noun", "en": "carrot", "jp": "にんじん" },
  { "emoji": "🥔", "word": "patata", "type": "noun", "en": "potato", "jp": "じゃがいも" },
  { "emoji": "🌽", "word": "maíz", "type": "noun", "en": "corn", "jp": "とうもろこし" },
  { "emoji": "🥒", "word": "pepino", "type": "noun", "en": "cucumber", "jp": "きゅうり" },
  { "emoji": "🥬", "word": "lechuga", "type": "noun", "en": "lettuce", "jp": "レタス" },
  { "emoji": "🍅", "word": "tomate", "type": "noun", "en": "tomato", "jp": "トマト" },
  { "emoji": "🧅", "word": "cebolla", "type": "noun", "en": "onion", "jp": "たまねぎ" },
  { "emoji": "🧄", "word": "ajo", "type": "noun", "en": "garlic", "jp": "にんにく" },
  { "emoji": "🥑", "word": "aguacate", "type": "noun", "en": "avocado", "jp": "アボカド" },
  { "emoji": "🍄", "word": "champiñón", "type": "noun", "en": "mushroom", "jp": "きのこ" },
  { "emoji": "🥜", "word": "cacahuete", "type": "noun", "en": "peanut", "jp": "ピーナッツ" },
  { "emoji": "🌰", "word": "castaña", "type": "noun", "en": "chestnut", "jp": "栗" },
  { "emoji": "🍞", "word": "pan", "type": "noun", "en": "bread", "jp": "パン" },
  { "emoji": "🥖", "word": "barra de pan", "type": "noun", "en": "baguette", "jp": "バゲット" },
  { "emoji": "🥨", "word": "pretzel", "type": "noun", "en": "pretzel", "jp": "プレッツェル" },
  { "emoji": "🥯", "word": "bagel", "type": "noun", "en": "bagel", "jp": "ベーグル" },
  { "emoji": "🥞", "word": "tortita", "type": "noun", "en": "pancake", "jp": "パンケーキ" },
  { "emoji": "🧇", "word": "gofre", "type": "noun", "en": "waffle", "jp": "ワッフル" },
  { "emoji": "🧀", "word": "queso", "type": "noun", "en": "cheese", "jp": "チーズ" },
  { "emoji": "🍖", "word": "carne", "type": "noun", "en": "meat", "jp": "肉" },
  { "emoji": "🍗", "word": "pollo", "type": "noun", "en": "chicken", "jp": "鶏肉" },
  { "emoji": "🥩", "word": "filete", "type": "noun", "en": "steak", "jp": "ステーキ" },
  { "emoji": "🥓", "word": "bacon", "type": "noun", "en": "bacon", "jp": "ベーコン" },
  { "emoji": "🍔", "word": "hamburguesa", "type": "noun", "en": "hamburger", "jp": "ハンバーガー" },
  { "emoji": "🌭", "word": "perrito caliente", "type": "noun", "en": "hot dog", "jp": "ホットドッグ" },
  { "emoji": "🥪", "word": "bocadillo", "type": "noun", "en": "sandwich", "jp": "サンドイッチ" },
  { "emoji": "🌮", "word": "taco", "type": "noun", "en": "taco", "jp": "タコス" },
  { "emoji": "🌯", "word": "burrito", "type": "noun", "en": "burrito", "jp": "ブリトー" },
  { "emoji": "🥚", "word": "huevo", "type": "noun", "en": "egg", "jp": "卵" },
  { "emoji": "🍤", "word": "gamba", "type": "noun", "en": "shrimp", "jp": "エビ" },
  { "emoji": "🦞", "word": "langosta", "type": "noun", "en": "lobster", "jp": "ロブスター" },
  { "emoji": "🦀", "word": "cangrejo", "type": "noun", "en": "crab", "jp": "カニ" },
  { "emoji": "🍣", "word": "sushi", "type": "noun", "en": "sushi", "jp": "寿司" },
  { "emoji": "🍚", "word": "arroz", "type": "noun", "en": "rice", "jp": "ご飯" },
  { "emoji": "🍜", "word": "ramen", "type": "noun", "en": "ramen", "jp": "ラーメン" },
  { "emoji": "🥟", "word": "empanadilla", "type": "noun", "en": "dumpling", "jp": "餃子" },
  { "emoji": "🍲", "word": "sopa", "type": "noun", "en": "soup", "jp": "スープ" },
  { "emoji": "🥗", "word": "ensalada", "type": "noun", "en": "salad", "jp": "サラダ" },
  { "emoji": "🍿", "word": "palomitas", "type": "noun", "en": "popcorn", "jp": "ポップコーン" },
  { "emoji": "🥫", "word": "lata", "type": "noun", "en": "can", "jp": "缶" },
  { "emoji": "🍪", "word": "galleta", "type": "noun", "en": "cookie", "jp": "クッキー" },
  { "emoji": "🍩", "word": "dónut", "type": "noun", "en": "donut", "jp": "ドーナツ" },
  { "emoji": "🍮", "word": "flan", "type": "noun", "en": "custard", "jp": "プリン" },
  { "emoji": "🍨", "word": "helado", "type": "noun", "en": "ice cream", "jp": "アイスクリーム" },
  { "emoji": "☕", "word": "café", "type": "noun", "en": "coffee", "jp": "コーヒー" },
  { "emoji": "🍵", "word": "té", "type": "noun", "en": "tea", "jp": "お茶" },
  { "emoji": "🥤", "word": "refresco", "type": "noun", "en": "soda", "jp": "ソーダ" },
  { "emoji": "🧃", "word": "zumo", "type": "noun", "en": "juice", "jp": "ジュース" },
  { "emoji": "🍷", "word": "vino", "type": "noun", "en": "wine", "jp": "ワイン" },
  { "emoji": "🍺", "word": "cerveza", "type": "noun", "en": "beer", "jp": "ビール" },
  { "emoji": "🍶", "word": "sake", "type": "noun", "en": "sake", "jp": "日本酒" },
  { "emoji": "🥃", "word": "whisky", "type": "noun", "en": "whisky", "jp": "ウイスキー" },
  { "emoji": "🍹", "word": "cóctel", "type": "noun", "en": "cocktail", "jp": "カクテル" },
  { "emoji": "🧂", "word": "sal", "type": "noun", "en": "salt", "jp": "塩" },
  { "emoji": "🍯", "word": "miel", "type": "noun", "en": "honey", "jp": "はちみつ" },
  { "emoji": "🧈", "word": "mantequilla", "type": "noun", "en": "butter", "jp": "バター" },
  { "emoji": "🥄", "word": "cuchara", "type": "noun", "en": "spoon", "jp": "スプーン" },
  { "emoji": "🥢", "word": "palillos", "type": "noun", "en": "chopsticks", "jp": "箸" },
  { "emoji": "🍽️", "word": "plato", "type": "noun", "en": "plate", "jp": "皿" },
  { "emoji": "🥣", "word": "cuenco", "type": "noun", "en": "bowl", "jp": "ボウル" },
  { "emoji": "🥤", "word": "vaso", "type": "noun", "en": "glass", "jp": "グラス" },
  { "emoji": "🍴", "word": "tenedor", "type": "noun", "en": "fork", "jp": "フォーク" },
  { "emoji": "🔪", "word": "cuchillo", "type": "noun", "en": "knife", "jp": "ナイフ" },
  { "emoji": "👩‍⚕️", "word": "médica", "type": "noun", "en": "doctor (f)", "jp": "医者（女性）" },
  { "emoji": "👨‍⚕️", "word": "médico", "type": "noun", "en": "doctor (m)", "jp": "医者（男性）" },
  { "emoji": "👩‍🏫", "word": "profesora", "type": "noun", "en": "teacher (f)", "jp": "教師（女性）" },
  { "emoji": "👨‍🏫", "word": "profesor", "type": "noun", "en": "teacher (m)", "jp": "教師（男性）" },
  { "emoji": "👩‍🚒", "word": "bombera", "type": "noun", "en": "firefighter (f)", "jp": "消防士（女性）" },
  { "emoji": "👨‍🚒", "word": "bombero", "type": "noun", "en": "firefighter (m)", "jp": "消防士（男性）" },
  { "emoji": "👩‍✈️", "word": "piloto", "type": "noun", "en": "pilot (f)", "jp": "パイロット（女性）" },
  { "emoji": "👨‍✈️", "word": "piloto", "type": "noun", "en": "pilot (m)", "jp": "パイロット（男性）" },
  { "emoji": "👩‍🍳", "word": "cocinera", "type": "noun", "en": "cook (f)", "jp": "料理人（女性）" },
  { "emoji": "👨‍🍳", "word": "cocinero", "type": "noun", "en": "cook (m)", "jp": "料理人（男性）" },
  { "emoji": "👩‍🌾", "word": "agricultora", "type": "noun", "en": "farmer (f)", "jp": "農家（女性）" },
  { "emoji": "👨‍🌾", "word": "agricultor", "type": "noun", "en": "farmer (m)", "jp": "農家（男性）" },
  { "emoji": "👩‍💼", "word": "oficinista", "type": "noun", "en": "office worker (f)", "jp": "事務員（女性）" },
  { "emoji": "👩‍🔧", "word": "mecánica", "type": "noun", "en": "mechanic (f)", "jp": "整備士（女性）" },
  { "emoji": "👨‍🔧", "word": "mecánico", "type": "noun", "en": "mechanic (m)", "jp": "整備士（男性）" },
  { "emoji": "👩‍🔬", "word": "científica", "type": "noun", "en": "scientist (f)", "jp": "科学者（女性）" },
  { "emoji": "👨‍🔬", "word": "científico", "type": "noun", "en": "scientist (m)", "jp": "科学者（男性）" },
  { "emoji": "👩‍🎨", "word": "artista", "type": "noun", "en": "artist (f)", "jp": "芸術家（女性）" },
  { "emoji": "👩‍🚀", "word": "astronauta", "type": "noun", "en": "astronaut (f)", "jp": "宇宙飛行士（女性）" },
  { "emoji": "👩‍⚖️", "word": "jueza", "type": "noun", "en": "judge (f)", "jp": "裁判官（女性）" },
  { "emoji": "👨‍⚖️", "word": "juez", "type": "noun", "en": "judge (m)", "jp": "裁判官（男性）" },
  { "emoji": "👮‍♀️", "word": "policía", "type": "noun", "en": "police officer (f)", "jp": "警察官（女性）" },
  { "emoji": "🕵️‍♀️", "word": "detective", "type": "noun", "en": "detective (f)", "jp": "探偵（女性）" },
  { "emoji": "💂‍♀️", "word": "guardia", "type": "noun", "en": "guard (f)", "jp": "衛兵（女性）" },
  { "emoji": "👷‍♀️", "word": "obrera", "type": "noun", "en": "construction worker (f)", "jp": "建設作業員（女性）" },
  { "emoji": "👷‍♂️", "word": "obrero", "type": "noun", "en": "construction worker (m)", "jp": "建設作業員（男性）" },
  { "emoji": "👩‍🎤", "word": "cantante", "type": "noun", "en": "singer (f)", "jp": "歌手（女性）" },
  { "emoji": "👩‍🏭", "word": "trabajadora", "type": "noun", "en": "worker (f)", "jp": "労働者（女性）" },
  { "emoji": "👨‍🏭", "word": "trabajador", "type": "noun", "en": "worker (m)", "jp": "労働者（男性）" },
  { "emoji": "👩‍💻", "word": "programadora", "type": "noun", "en": "programmer (f)", "jp": "プログラマー（女性）" },
  { "emoji": "👨‍💻", "word": "programador", "type": "noun", "en": "programmer (m)", "jp": "プログラマー（男性）" },
  { "emoji": "👩‍🌐", "word": "traductora", "type": "noun", "en": "translator (f)", "jp": "翻訳者（女性）" },
  { "emoji": "👨‍🌐", "word": "traductor", "type": "noun", "en": "translator (m)", "jp": "翻訳者（男性）" },
  { "emoji": "👨‍🎓", "word": "estudiante", "type": "noun", "en": "student (m)", "jp": "学生（男性）" },
  { "emoji": "🧑‍⚕️", "word": "enfermero", "type": "noun", "en": "nurse", "jp": "看護師" },
  { "emoji": "🧑‍🚒", "word": "paramédico", "type": "noun", "en": "paramedic", "jp": "救急救命士" },
  { "emoji": "🧑‍🔧", "word": "técnico", "type": "noun", "en": "technician", "jp": "技術者" },
  { "emoji": "🧑‍🌾", "word": "jardinero", "type": "noun", "en": "gardener", "jp": "庭師" },
  { "emoji": "🧑‍🍳", "word": "chef", "type": "noun", "en": "chef", "jp": "シェフ" },
  { "emoji": "🧑‍🎤", "word": "músico", "type": "noun", "en": "musician", "jp": "音楽家" },
  { "emoji": "🧑‍🎨", "word": "pintor", "type": "noun", "en": "painter", "jp": "画家" },
  { "emoji": "🧑‍💼", "word": "gerente", "type": "noun", "en": "manager", "jp": "マネージャー" },
  { "emoji": "🧑‍⚖️", "word": "abogado", "type": "noun", "en": "lawyer", "jp": "弁護士" },
  { "emoji": "🧑‍🔬", "word": "investigador", "type": "noun", "en": "researcher", "jp": "研究者" },
  { "emoji": "🧑‍💻", "word": "ingeniero", "type": "noun", "en": "engineer", "jp": "エンジニア" },
  { "emoji": "🧑‍🏫", "word": "maestro", "type": "noun", "en": "teacher", "jp": "先生" },
  { "emoji": "🧑‍🚀", "word": "astronauta", "type": "noun", "en": "astronaut", "jp": "宇宙飛行士" },
  { "emoji": "🧑‍⚕️", "word": "farmacéutico", "type": "noun", "en": "pharmacist", "jp": "薬剤師" },
  { "emoji": "🧑‍🌐", "word": "escritor", "type": "noun", "en": "writer", "jp": "作家" },
  { "emoji": "🧑‍🎓", "word": "alumno", "type": "noun", "en": "student", "jp": "生徒" },
  { "emoji": "🧑‍🎤", "word": "actor", "type": "noun", "en": "actor", "jp": "俳優" },
  { "emoji": "🧑‍🏭", "word": "operario", "type": "noun", "en": "operator", "jp": "オペレーター" },
  { "emoji": "🧑‍✈️", "word": "capitán", "type": "noun", "en": "captain", "jp": "船長" },
  { "emoji": "🚗", "word": "coche", "type": "noun", "en": "car", "jp": "車" },
  { "emoji": "📚", "word": "libro", "type": "noun", "en": "book", "jp": "本" },
  { "emoji": "⚽", "word": "balón", "type": "noun", "en": "ball", "jp": "ボール" },
  { "emoji": "🚲", "word": "bici", "type": "noun", "en": "bike", "jp": "自転車" },
  { "emoji": "🪁", "word": "cometa", "type": "noun", "en": "kite", "jp": "凧" },
  { "emoji": "🎈", "word": "globo", "type": "noun", "en": "balloon", "jp": "風船" },
  { "emoji": "🪑", "word": "silla", "type": "noun", "en": "chair", "jp": "椅子" },
  { "emoji": "🛋️", "word": "sofá", "type": "noun", "en": "sofa", "jp": "ソファ" },
  { "emoji": "🛏️", "word": "cama", "type": "noun", "en": "bed", "jp": "ベッド" },
  { "emoji": "🪴", "word": "planta", "type": "noun", "en": "plant", "jp": "植物" },
  { "emoji": "🖼️", "word": "cuadro", "type": "noun", "en": "painting", "jp": "絵画" },
  { "emoji": "🪞", "word": "espejo", "type": "noun", "en": "mirror", "jp": "鏡" },
  { "emoji": "🪟", "word": "ventana", "type": "noun", "en": "window", "jp": "窓" },
  { "emoji": "🚪", "word": "puerta", "type": "noun", "en": "door", "jp": "ドア" },
  { "emoji": "🔑", "word": "llave", "type": "noun", "en": "key", "jp": "鍵" },
  { "emoji": "🔒", "word": "candado", "type": "noun", "en": "lock", "jp": "錠前" },
  { "emoji": "🧳", "word": "maleta", "type": "noun", "en": "suitcase", "jp": "スーツケース" },
  { "emoji": "🎒", "word": "mochila", "type": "noun", "en": "backpack", "jp": "リュック" },
  { "emoji": "👜", "word": "bolso", "type": "noun", "en": "bag", "jp": "バッグ" },
  { "emoji": "👛", "word": "monedero", "type": "noun", "en": "wallet", "jp": "財布" },
  { "emoji": "🖌️", "word": "pincel", "type": "noun", "en": "paintbrush", "jp": "絵筆" },
  { "emoji": "✏️", "word": "lápiz", "type": "noun", "en": "pencil", "jp": "鉛筆" },
  { "emoji": "🖊️", "word": "bolígrafo", "type": "noun", "en": "pen", "jp": "ペン" },
  { "emoji": "📏", "word": "regla", "type": "noun", "en": "ruler", "jp": "定規" },
  { "emoji": "✂️", "word": "tijeras", "type": "noun", "en": "scissors", "jp": "はさみ" },
  { "emoji": "📎", "word": "clip", "type": "noun", "en": "paperclip", "jp": "クリップ" },
  { "emoji": "📋", "word": "tablón", "type": "noun", "en": "board", "jp": "ボード" },
  { "emoji": "📌", "word": "chincheta", "type": "noun", "en": "thumbtack", "jp": "画鋲" },
  { "emoji": "📍", "word": "tachuela", "type": "noun", "en": "tack", "jp": "タック" },
  { "emoji": "🧷", "word": "imperdible", "type": "noun", "en": "safety pin", "jp": "安全ピン" },
  { "emoji": "🪚", "word": "sierra", "type": "noun", "en": "saw", "jp": "のこぎり" },
  { "emoji": "🔧", "word": "llave inglesa", "type": "noun", "en": "wrench", "jp": "レンチ" },
  { "emoji": "🪛", "word": "destornillador", "type": "noun", "en": "screwdriver", "jp": "ドライバー" },
  { "emoji": "🔨", "word": "martillo", "type": "noun", "en": "hammer", "jp": "ハンマー" },
  { "emoji": "🪓", "word": "hacha", "type": "noun", "en": "axe", "jp": "斧" },
  { "emoji": "⛏️", "word": "pico", "type": "noun", "en": "pickaxe", "jp": "つるはし" },
  { "emoji": "🪝", "word": "gancho", "type": "noun", "en": "hook", "jp": "フック" },
  { "emoji": "🧹", "word": "escoba", "type": "noun", "en": "broom", "jp": "ほうき" },
  { "emoji": "🪣", "word": "cubo", "type": "noun", "en": "bucket", "jp": "バケツ" },
  { "emoji": "🧽", "word": "esponja", "type": "noun", "en": "sponge", "jp": "スポンジ" },
  { "emoji": "🧼", "word": "jabón", "type": "noun", "en": "soap", "jp": "石鹸" },
  { "emoji": "🧴", "word": "loción", "type": "noun", "en": "lotion", "jp": "ローション" },
  { "emoji": "🪒", "word": "maquinilla", "type": "noun", "en": "razor", "jp": "かみそり" },
  { "emoji": "💡", "word": "bombilla", "type": "noun", "en": "light bulb", "jp": "電球" },
  { "emoji": "🔦", "word": "linterna", "type": "noun", "en": "flashlight", "jp": "懐中電灯" },
  { "emoji": "🕯️", "word": "vela", "type": "noun", "en": "candle", "jp": "ろうそく" },
  { "emoji": "🪔", "word": "lámpara", "type": "noun", "en": "lamp", "jp": "ランプ" },
  { "emoji": "📺", "word": "tele", "type": "noun", "en": "TV", "jp": "テレビ" },
  { "emoji": "📻", "word": "radio", "type": "noun", "en": "radio", "jp": "ラジオ" },
  { "emoji": "💻", "word": "ordenador", "type": "noun", "en": "computer", "jp": "コンピューター" },
  { "emoji": "📱", "word": "móvil", "type": "noun", "en": "phone", "jp": "携帯電話" },
  { "emoji": "⌚", "word": "reloj", "type": "noun", "en": "watch", "jp": "時計" },
  { "emoji": "⏰", "word": "despertador", "type": "noun", "en": "alarm clock", "jp": "目覚まし時計" },
  { "emoji": "📷", "word": "cámara", "type": "noun", "en": "camera", "jp": "カメラ" },
  { "emoji": "🎥", "word": "videocámara", "type": "noun", "en": "video camera", "jp": "ビデオカメラ" },
  { "emoji": "🎤", "word": "micrófono", "type": "noun", "en": "microphone", "jp": "マイク" },
  { "emoji": "🎧", "word": "cascos", "type": "noun", "en": "headphones", "jp": "ヘッドホン" },
  { "emoji": "🖨️", "word": "impresora", "type": "noun", "en": "printer", "jp": "プリンター" },
  { "emoji": "🖱️", "word": "ratón", "type": "noun", "en": "mouse", "jp": "マウス" },
  { "emoji": "⌨️", "word": "teclado", "type": "noun", "en": "keyboard", "jp": "キーボード" },
  { "emoji": "💾", "word": "disco", "type": "noun", "en": "disk", "jp": "ディスク" },
  { "emoji": "🪢", "word": "cuerda", "type": "noun", "en": "rope", "jp": "ロープ" },
  { "emoji": "🧶", "word": "lana", "type": "noun", "en": "wool", "jp": "毛糸" },
  { "emoji": "🪡", "word": "aguja", "type": "noun", "en": "needle", "jp": "針" },
  { "emoji": "🧵", "word": "hilo", "type": "noun", "en": "thread", "jp": "糸" },
  { "emoji": "🪜", "word": "escalera", "type": "noun", "en": "ladder", "jp": "はしご" },
  { "emoji": "🛠️", "word": "herramienta", "type": "noun", "en": "tool", "jp": "道具" },
  { "emoji": "🪞", "word": "espejo", "type": "noun", "en": "mirror", "jp": "鏡" },
  { "emoji": "🧺", "word": "cesto", "type": "noun", "en": "basket", "jp": "かご" },
  { "emoji": "🛒", "word": "carrito", "type": "noun", "en": "cart", "jp": "カート" },
  { "emoji": "🧲", "word": "imán", "type": "noun", "en": "magnet", "jp": "磁石" },
  { "emoji": "🪤", "word": "trampa", "type": "noun", "en": "trap", "jp": "わな" },
  { "emoji": "📦", "word": "caja", "type": "noun", "en": "box", "jp": "箱" },
  { "emoji": "🧳", "word": "maleta", "type": "noun", "en": "suitcase", "jp": "スーツケース" },
  { "emoji": "🗑️", "word": "cubo de basura", "type": "noun", "en": "trash can", "jp": "ごみ箱" },
  { "emoji": "🪥", "word": "cepillo de dientes", "type": "noun", "en": "toothbrush", "jp": "歯ブラシ" },
  { "emoji": "🧻", "word": "papel", "type": "noun", "en": "paper", "jp": "紙" },
  { "emoji": "🪦", "word": "lápida", "type": "noun", "en": "tombstone", "jp": "墓石" },
  { "emoji": "🪳", "word": "cucaracha", "type": "noun", "en": "cockroach", "jp": "ゴキブリ" },
  { "emoji": "🪰", "word": "mosca", "type": "noun", "en": "fly", "jp": "ハエ" },
  { "emoji": "🕸️", "word": "telaraña", "type": "noun", "en": "spider web", "jp": "クモの巣" },
  { "emoji": "🏠", "word": "casa", "type": "noun", "en": "house", "jp": "家" },
  { "emoji": "🏫", "word": "colegio", "type": "noun", "en": "school", "jp": "学校" },
  { "emoji": "🏖️", "word": "playa", "type": "noun", "en": "beach", "jp": "ビーチ" },
  { "emoji": "🏰", "word": "castillo", "type": "noun", "en": "castle", "jp": "城" },
  { "emoji": "🏡", "word": "hogar", "type": "noun", "en": "home", "jp": "家庭" },
  { "emoji": "🏬", "word": "tienda", "type": "noun", "en": "store", "jp": "店" },
  { "emoji": "🏥", "word": "hospital", "type": "noun", "en": "hospital", "jp": "病院" },
  { "emoji": "⛪", "word": "iglesia", "type": "noun", "en": "church", "jp": "教会" },
  { "emoji": "🏢", "word": "oficina", "type": "noun", "en": "office", "jp": "オフィス" },
  { "emoji": "🏦", "word": "banco", "type": "noun", "en": "bank", "jp": "銀行" },
  { "emoji": "🏛️", "word": "museo", "type": "noun", "en": "museum", "jp": "博物館" },
  { "emoji": "🏨", "word": "hotel", "type": "noun", "en": "hotel", "jp": "ホテル" },
  { "emoji": "🕌", "word": "mezquita", "type": "noun", "en": "mosque", "jp": "モスク" },
  { "emoji": "🕍", "word": "sinagoga", "type": "noun", "en": "synagogue", "jp": "シナゴーグ" },
  { "emoji": "⛩️", "word": "templo", "type": "noun", "en": "temple", "jp": "寺" },
  { "emoji": "🏤", "word": "correos", "type": "noun", "en": "post office", "jp": "郵便局" },
  { "emoji": "🏟️", "word": "estadio", "type": "noun", "en": "stadium", "jp": "スタジアム" },
  { "emoji": "🎡", "word": "parque", "type": "noun", "en": "park", "jp": "公園" },
  { "emoji": "🌳", "word": "bosque", "type": "noun", "en": "forest", "jp": "森" },
  { "emoji": "⛰️", "word": "montaña", "type": "noun", "en": "mountain", "jp": "山" },
  { "emoji": "🌊", "word": "mar", "type": "noun", "en": "sea", "jp": "海" },
  { "emoji": "🏜️", "word": "desierto", "type": "noun", "en": "desert", "jp": "砂漠" },
  { "emoji": "🏝️", "word": "isla", "type": "noun", "en": "island", "jp": "島" },
  { "emoji": "🌄", "word": "valle", "type": "noun", "en": "valley", "jp": "谷" },
  { "emoji": "🌋", "word": "volcán", "type": "noun", "en": "volcano", "jp": "火山" },
  { "emoji": "🏕️", "word": "campamento", "type": "noun", "en": "camp", "jp": "キャンプ" },
  { "emoji": "🛤️", "word": "ferrocarril", "type": "noun", "en": "railway", "jp": "鉄道" },
  { "emoji": "🛣️", "word": "carretera", "type": "noun", "en": "road", "jp": "道路" },
  { "emoji": "🌉", "word": "puente", "type": "noun", "en": "bridge", "jp": "橋" },
  { "emoji": "🗽", "word": "estatua", "type": "noun", "en": "statue", "jp": "像" },
  { "emoji": "🗼", "word": "torre", "type": "noun", "en": "tower", "jp": "塔" },
  { "emoji": "🏭", "word": "fábrica", "type": "noun", "en": "factory", "jp": "工場" },
  { "emoji": "🛬", "word": "aeropuerto", "type": "noun", "en": "airport", "jp": "空港" },
  { "emoji": "🛥️", "word": "puerto", "type": "noun", "en": "port", "jp": "港" },
  { "emoji": "🗻", "word": "monte", "type": "noun", "en": "mount", "jp": "山" },
  { "emoji": "🏙️", "word": "ciudad", "type": "noun", "en": "city", "jp": "都市" },
  { "emoji": "🌆", "word": "pueblo", "type": "noun", "en": "town", "jp": "町" },
  { "emoji": "🏚️", "word": "ruina", "type": "noun", "en": "ruin", "jp": "廃墟" },
  { "emoji": "🛖", "word": "cabaña", "type": "noun", "en": "cabin", "jp": "小屋" },
  { "emoji": "⛺", "word": "tienda", "type": "noun", "en": "tent", "jp": "テント" },
  { "emoji": "🌇", "word": "atardecer", "type": "noun", "en": "sunset", "jp": "夕日" },
  { "emoji": "🌌", "word": "cielo", "type": "noun", "en": "sky", "jp": "空" },
  { "emoji": "🪨", "word": "roca", "type": "noun", "en": "rock", "jp": "岩" },
  { "emoji": "🪵", "word": "leña", "type": "noun", "en": "firewood", "jp": "薪" },
  { "emoji": "🪴", "word": "jardín", "type": "noun", "en": "garden", "jp": "庭" },
  { "emoji": "🛝", "word": "tobogán", "type": "noun", "en": "slide", "jp": "滑り台" },
  { "emoji": "🎠", "word": "carrusel", "type": "noun", "en": "carousel", "jp": "メリーゴーランド" },
  { "emoji": "⛲", "word": "fuente", "type": "noun", "en": "fountain", "jp": "噴水" },
  { "emoji": "🛤", "word": "estación", "type": "noun", "en": "station", "jp": "駅" },
  { "emoji": "🛫", "word": "pista", "type": "noun", "en": "runway", "jp": "滑走路" },
  { "emoji": "🗿", "word": "monumento", "type": "noun", "en": "monument", "jp": "記念碑" },
  { "emoji": "🪦", "word": "cementerio", "type": "noun", "en": "cemetery", "jp": "墓地" },
  { "emoji": "🛟", "word": "muelle", "type": "noun", "en": "dock", "jp": "埠頭" },
  { "emoji": "🪸", "word": "arrecife", "type": "noun", "en": "reef", "jp": "礁" },
  { "emoji": "🛳️", "word": "crucero", "type": "noun", "en": "cruise", "jp": "クルーズ" },
  { "emoji": "🛕", "word": "pagoda", "type": "noun", "en": "pagoda", "jp": "パゴダ" },
  { "emoji": "🪧", "word": "letrero", "type": "noun", "en": "sign", "jp": "看板" },
  { "emoji": "🛗", "word": "ascensor", "type": "noun", "en": "elevator", "jp": "エレベーター" },
  { "emoji": "🪜", "word": "escalera", "type": "noun", "en": "ladder", "jp": "はしご" },
  { "emoji": "🛁", "word": "bañera", "type": "noun", "en": "bathtub", "jp": "浴槽" },
  { "emoji": "🍽️", "word": "cocina", "type": "noun", "en": "kitchen", "jp": "キッチン" },
  { "emoji": "🛋️", "word": "sala", "type": "noun", "en": "living room", "jp": "リビング" },
  { "emoji": "🛏️", "word": "dormitorio", "type": "noun", "en": "bedroom", "jp": "寝室" },
  { "emoji": "🪑", "word": "comedor", "type": "noun", "en": "dining room", "jp": "ダイニング" },
  { "emoji": "🖼️", "word": "galería", "type": "noun", "en": "gallery", "jp": "ギャラリー" },
  { "emoji": "🛒", "word": "mercado", "type": "noun", "en": "market", "jp": "市場 (いちば)" },
  { "emoji": "🎢", "word": "montaña rusa", "type": "noun", "en": "roller coaster", "jp": "ジェットコースター" },
  { "emoji": "🚗", "word": "garaje", "type": "noun", "en": "garage", "jp": "ガレージ" }, // Adjusted emoji (🪝→🚗)
  { "emoji": "🏙️", "word": "balcón", "type": "noun", "en": "balcony", "jp": "バルコニー" }, // Adjusted emoji (🪟→🏙️)
  { "emoji": "⚽", "word": "fútbol", "type": "noun", "en": "football/soccer", "jp": "サッカー" },
  { "emoji": "🏀", "word": "baloncesto", "type": "noun", "en": "basketball", "jp": "バスケットボール" },
  { "emoji": "🏐", "word": "voleibol", "type": "noun", "en": "volleyball", "jp": "バレーボール" },
  { "emoji": "🎾", "word": "tenis", "type": "noun", "en": "tennis", "jp": "テニス" },
  { "emoji": "🏈", "word": "fútbol americano", "type": "noun", "en": "American football", "jp": "アメリカンフットボール" },
  { "emoji": "🏉", "word": "rugby", "type": "noun", "en": "rugby", "jp": "ラグビー" },
  { "emoji": "🏑", "word": "hockey", "type": "noun", "en": "field hockey", "jp": "ホッケー" },
  { "emoji": "🏒", "word": "hockey sobre hielo", "type": "noun", "en": "ice hockey", "jp": "アイスホッケー" },
  { "emoji": "🏓", "word": "ping pong", "type": "noun", "en": "table tennis", "jp": "卓球 (たっきゅう)" },
  { "emoji": "🏸", "word": "bádminton", "type": "noun", "en": "badminton", "jp": "バドミントン" },
  { "emoji": "🥊", "word": "boxeo", "type": "noun", "en": "boxing", "jp": "ボクシング" },
  { "emoji": "🥋", "word": "karate", "type": "noun", "en": "karate", "jp": "空手 (からて)" },
  { "emoji": "🤼", "word": "lucha libre", "type": "noun", "en": "wrestling", "jp": "レスリング" },
  { "emoji": "🤺", "word": "esgrima", "type": "noun", "en": "fencing", "jp": "フェンシング" },
  { "emoji": "🏋️", "word": "levantamiento de pesas", "type": "noun", "en": "weightlifting", "jp": "重量挙げ (じゅうりょうあげ)" },
  { "emoji": "🤸", "word": "gimnasia", "type": "noun", "en": "gymnastics", "jp": "体操 (たいそう)" },
  { "emoji": "🏊", "word": "natación", "type": "noun", "en": "swimming", "jp": "水泳 (すいえい)" },
  { "emoji": "🏄", "word": "surf", "type": "noun", "en": "surfing", "jp": "サーフィン" },
  { "emoji": "🤽", "word": "waterpolo", "type": "noun", "en": "water polo", "jp": "水球 (すいきゅう)" },
  { "emoji": "🚣", "word": "remo", "type": "noun", "en": "rowing", "jp": "ボート競技 (ぼーときょうぎ)" },
  { "emoji": "🛶", "word": "piragüismo", "type": "noun", "en": "canoeing", "jp": "カヌー" }, // Adjusted word (canotaje→piragüismo)
  { "emoji": "🚴", "word": "ciclismo", "type": "noun", "en": "cycling", "jp": "サイクリング" },
  { "emoji": "🏍️", "word": "motociclismo", "type": "noun", "en": "motorcycling", "jp": "モーターサイクル" },
  { "emoji": "🏎️", "word": "automovilismo", "type": "noun", "en": "motorsport", "jp": "モータースポーツ" },
  { "emoji": "🏇", "word": "equitación", "type": "noun", "en": "horse riding", "jp": "乗馬 (じょうば)" },
  { "emoji": "⛸️", "word": "patinaje", "type": "noun", "en": "skating", "jp": "スケート" },
  { "emoji": "⛷️", "word": "esquí", "type": "noun", "en": "skiing", "jp": "スキー" },
  { "emoji": "🏂", "word": "snowboard", "type": "noun", "en": "snowboarding", "jp": "スノーボード" },
  { "emoji": "🥌", "word": "curling", "type": "noun", "en": "curling", "jp": "カーリング" },
  { "emoji": "🎿", "word": "esquí alpino", "type": "noun", "en": "alpine skiing", "jp": "アルペンスキー" },
  { "emoji": "🏹", "word": "tiro con arco", "type": "noun", "en": "archery", "jp": "アーチェリー" },
  { "emoji": "🎯", "word": "diana", "type": "noun", "en": "target", "jp": "的 (まと)" },
  { "emoji": "🥍", "word": "lacrosse", "type": "noun", "en": "lacrosse", "jp": "ラクロス" },
  { "emoji": "🏏", "word": "críquet", "type": "noun", "en": "cricket", "jp": "クリケット" },
  { "emoji": "🥏", "word": "frisbee", "type": "noun", "en": "frisbee", "jp": "フリスビー" },
  { "emoji": "🎳", "word": "bolos", "type": "noun", "en": "bowling", "jp": "ボウリング" }, // Adjusted word (boliche→bolos)
  { "emoji": "🎱", "word": "billar", "type": "noun", "en": "pool", "jp": "ビリヤード" },
  { "emoji": "🎲", "word": "dados", "type": "noun", "en": "dice", "jp": "サイコロ" },
  { "emoji": "♟️", "word": "ajedrez", "type": "noun", "en": "chess", "jp": "チェス" },
  { "emoji": "🎮", "word": "videojuegos", "type": "noun", "en": "video games", "jp": "ビデオゲーム" },
  { "emoji": "🧩", "word": "puzle", "type": "noun", "en": "puzzle", "jp": "パズル" }, // Adjusted word (rompecabezas→puzle)
  { "emoji": "🪁", "word": "cometa", "type": "noun", "en": "kite", "jp": "凧 (たこ)" }, // Adjusted word (papalote→cometa)
  { "emoji": "🪂", "word": "paracaidismo", "type": "noun", "en": "parachuting", "jp": "パラシュート" },
  { "emoji": "🪀", "word": "yoyó", "type": "noun", "en": "yo-yo", "jp": "ヨーヨー" },
  { "emoji": "🧗", "word": "escalada", "type": "noun", "en": "climbing", "jp": "クライミング" },
  { "emoji": "🤾", "word": "balonmano", "type": "noun", "en": "handball", "jp": "ハンドボール" }, // Adjusted word (handball→balonmano)
  { "emoji": "🏅", "word": "medalla", "type": "noun", "en": "medal", "jp": "メダル" },
  { "emoji": "🏆", "word": "trofeo", "type": "noun", "en": "trophy", "jp": "トロフィー" },
  { "emoji": "🥇", "word": "oro", "type": "noun", "en": "gold", "jp": "金 (きん)" },
  { "emoji": "🥈", "word": "plata", "type": "noun", "en": "silver", "jp": "銀 (ぎん)" },
  { "emoji": "🥉", "word": "bronce", "type": "noun", "en": "bronze", "jp": "銅 (どう)" },
  { "emoji": "🧘", "word": "yoga", "type": "noun", "en": "yoga", "jp": "ヨガ" },
  { "emoji": "🏃", "word": "correr", "type": "verb", "en": "to run", "jp": "走る (はしる)" },
  { "emoji": "🚶", "word": "caminar", "type": "verb", "en": "to walk", "jp": "歩く (あるく)" },
  { "emoji": "🏊", "word": "nadar", "type": "verb", "en": "to swim", "jp": "泳ぐ (およぐ)" },
  { "emoji": "🚴", "word": "pedalear", "type": "verb", "en": "to pedal", "jp": "ペダルをこぐ" },
  { "emoji": "🤸", "word": "saltar", "type": "verb", "en": "to jump", "jp": "跳ぶ (とぶ)" },
  { "emoji": "🏋️", "word": "levantar", "type": "verb", "en": "to lift", "jp": "持ち上げる (もちあげる)" },
  { "emoji": "🏄", "word": "hacer surf", "type": "verb", "en": "to surf", "jp": "サーフィンする" }, // Adjusted word (surfear→hacer surf)
  { "emoji": "⛷️", "word": "esquiar", "type": "verb", "en": "to ski", "jp": "スキーする" },
  { "emoji": "🚣", "word": "remar", "type": "verb", "en": "to row", "jp": "漕ぐ (こぐ)" },
  { "emoji": "🎳", "word": "jugar a los bolos", "type": "verb", "en": "to bowl", "jp": "ボウリングする" }, // Adjusted word (bolear→jugar a los bolos)
  { "emoji": "🏸", "word": "jugar al bádminton", "type": "verb", "en": "to play badminton", "jp": "バドミントンをする" },
  { "emoji": "🏓", "word": "jugar al ping pong", "type": "verb", "en": "to play ping pong", "jp": "卓球をする" },
  { "emoji": "🎾", "word": "jugar al tenis", "type": "verb", "en": "to play tennis", "jp": "テニスをする" },
  { "emoji": "⚽", "word": "jugar al fútbol", "type": "verb", "en": "to play football", "jp": "サッカーをする" },
  { "emoji": "🏀", "word": "jugar al baloncesto", "type": "verb", "en": "to play basketball", "jp": "バスケットボールをする" },
  { "emoji": "🥊", "word": "boxear", "type": "verb", "en": "to box", "jp": "ボクシングする" },
  { "emoji": "🤺", "word": "esgrimir", "type": "verb", "en": "to fence", "jp": "フェンシングする" },
  { "emoji": "☀️", "word": "día", "type": "noun", "en": "day", "jp": "日 (ひ)" },
  { "emoji": "🌙", "word": "noche", "type": "noun", "en": "night", "jp": "夜 (よる)" },
  { "emoji": "🌞", "word": "mañana", "type": "noun", "en": "morning", "jp": "朝 (あさ)" },
  { "emoji": "🌅", "word": "amanecer", "type": "noun", "en": "sunrise", "jp": "夜明け (よあけ)" },
  { "emoji": "🌇", "word": "atardecer", "type": "noun", "en": "sunset", "jp": "夕暮れ (ゆうぐれ)" },
  { "emoji": "🌌", "word": "medianoche", "type": "noun", "en": "midnight", "jp": "真夜中 (まよなか)" },
  { "emoji": "⏰", "word": "hora", "type": "noun", "en": "hour", "jp": "時間 (じかん)" },
  { "emoji": "⌚", "word": "minuto", "type": "noun", "en": "minute", "jp": "分 (ふん)" },
  { "emoji": "⏳", "word": "segundo", "type": "noun", "en": "second", "jp": "秒 (びょう)" },
  { "emoji": "📅", "word": "calendario", "type": "noun", "en": "calendar", "jp": "カレンダー" },
  { "emoji": "📆", "word": "fecha", "type": "noun", "en": "date", "jp": "日付 (ひづけ)" },
  { "emoji": "🕰️", "word": "reloj", "type": "noun", "en": "clock", "jp": "時計 (とけい)" },
  { "emoji": "🌸", "word": "primavera", "type": "noun", "en": "spring", "jp": "春 (はる)" },
  { "emoji": "🌻", "word": "verano", "type": "noun", "en": "summer", "jp": "夏 (なつ)" },
  { "emoji": "🍂", "word": "otoño", "type": "noun", "en": "autumn", "jp": "秋 (あき)" },
  { "emoji": "❄️", "word": "invierno", "type": "noun", "en": "winter", "jp": "冬 (ふゆ)" },
  { "emoji": "🗓️", "word": "mes", "type": "noun", "en": "month", "jp": "月 (つき)" },
  { "emoji": "📅", "word": "semana", "type": "noun", "en": "week", "jp": "週 (しゅう)" }, // Adjusted emoji (📇→📅)
  { "emoji": "🌄", "word": "alba", "type": "noun", "en": "dawn", "jp": "夜明け (よあけ)" },
  { "emoji": "🌆", "word": "crepúsculo", "type": "noun", "en": "twilight", "jp": "黄昏 (たそがれ)" },
  { "emoji": "🌕", "word": "mediodía", "type": "noun", "en": "noon", "jp": "正午 (しょうご)" },
  { "emoji": "🌗", "word": "tarde", "type": "noun", "en": "afternoon", "jp": "午後 (ごご)" },
  { "emoji": "🌑", "word": "madrugada", "type": "noun", "en": "early morning", "jp": "早朝 (そうちょう)" },
  { "emoji": "🌘", "word": "anochecer", "type": "noun", "en": "dusk", "jp": "日暮れ (ひぐれ)" },
  { "emoji": "🌅", "word": "matutino", "type": "adjective", "en": "morning (adj.)", "jp": "朝の (あさの)" },
  { "emoji": "🌇", "word": "vespertino", "type": "adjective", "en": "evening (adj.)", "jp": "夕方の (ゆうがたの)" },
  { "emoji": "🌙", "word": "nocturno", "type": "adjective", "en": "nocturnal", "jp": "夜の (よるの)" },
  { "emoji": "🗒️", "word": "agenda", "type": "noun", "en": "agenda", "jp": "予定表 (よていひょう)" },
  { "emoji": "⏱️", "word": "cronómetro", "type": "noun", "en": "stopwatch", "jp": "ストップウォッチ" },
  { "emoji": "⏲️", "word": "temporizador", "type": "noun", "en": "timer", "jp": "タイマー" },
  { "emoji": "📈", "word": "año", "type": "noun", "en": "year", "jp": "年 (ねん)" },
  { "emoji": "📊", "word": "década", "type": "noun", "en": "decade", "jp": "十年 (じゅうねん)" },
  { "emoji": "🗿", "word": "siglo", "type": "noun", "en": "century", "jp": "世紀 (せいき)" },
  { "emoji": "🌍", "word": "era", "type": "noun", "en": "era", "jp": "時代 (じだい)" },
  { "emoji": "📉", "word": "periodo", "type": "noun", "en": "period", "jp": "期間 (きかん)" }
];
